### ISSUE TITLE
CSS Bugs

### ISSUE THREAD

**Issue by withrvr** [Ayush-Bulbule/Portfolio-1#1]
# 1. when someone visit very first time

- dark/light mode doesn't show properly
![image](https://user-images.githubusercontent.com/69628500/215840415-77de5de8-6c9c-423e-a94a-7b02a2272480.png)

# 2. navigation not working properly

### Example
- skills

![image](https://user-images.githubusercontent.com/69628500/215840635-e294254e-30ee-43d9-8487-2e57106290ca.png)

- projects

![image](https://user-images.githubusercontent.com/69628500/215840669-cfc864bf-23d2-4bd3-9e47-b0cbecb7ee00.png)

### solution

- https://stackoverflow.com/questions/31905996/why-some-text-in-my-site-page-hidden-behind-navbar-bootstrap
- https://forum.freecodecamp.org/t/content-hiding-behind-nav-bar/395317

# 3. new tab

- open this external links in new tab
- also others in footer ... etc

![image](https://user-images.githubusercontent.com/69628500/215843351-a9431391-71a9-45e7-8ae5-398d3fb672c7.png)

# 4. lol ... Contact Me ... is for showcase

.

**Comment by Ayush-Bulbule** [comment]
Thanks Raghav for your feed back on my portfolio website. And thank you for providing the solutions also. I will resolve them as soon as possible.

**Comment by Ayush-Bulbule** [comment]
Issue is resolved!

**Comment by Ayush-Bulbule** [comment]
Contact Me is yet to implement!!😅
